#!/usr/bin/env python3
"""
init-docs.py — One-time bootstrapper for per-directory CLAUDE.md files.
Run once to seed documentation for every directory that needs it.
"""
import os
import subprocess
import textwrap
from pathlib import Path

SKIP_DIRS = {
    'node_modules', '.git', '__pycache__', 'dist', 'build',
    '.next', 'coverage', 'vendor', 'venv', '.venv', 'env',
    'migrations', 'generated', '.cache', 'tmp', 'temp',
    'prs', '_template', 'repo',  # sandbox runtime dirs
}

MIN_SOURCE_FILES = 2
SOURCE_EXTENSIONS = {
    '.py', '.ts', '.tsx', '.js', '.jsx', '.go',
    '.rs', '.rb', '.java', '.kt', '.swift', '.cpp', '.c'
}


def should_have_claude_md(dirpath: Path) -> bool:
    if dirpath.name in SKIP_DIRS or dirpath.name.startswith('.'):
        return False
    if any(part in SKIP_DIRS for part in dirpath.parts):
        return False
    source_files = [
        f for f in dirpath.iterdir()
        if f.is_file() and f.suffix in SOURCE_EXTENSIONS
        and not f.name.startswith('__')
    ]
    return len(source_files) >= MIN_SOURCE_FILES


def generate_claude_md(dirpath: Path, repo_root: Path) -> str:
    files = sorted([f for f in dirpath.iterdir() if f.is_file()])
    source_files = [f for f in files if f.suffix in SOURCE_EXTENSIONS and not f.name.startswith('__')]

    file_summaries = []
    for f in source_files[:10]:
        try:
            content = f.read_text(errors='replace')
            lines = content.splitlines()
            first_meaningful = next(
                (l.strip() for l in lines[:15]
                 if l.strip() and not l.strip().startswith(('#!', '#', 'import', 'from', '"""', "'''"))),
                ""
            )
            file_summaries.append(f"- `{f.name}`: {first_meaningful[:80]}" if first_meaningful else f"- `{f.name}`")
        except Exception:
            file_summaries.append(f"- `{f.name}`")

    rel = dirpath.relative_to(repo_root)
    return textwrap.dedent(f"""\
        # {dirpath.name}/

        <!-- AUTO-GENERATED by doc-sync. Edit Purpose and Key Patterns freely — they are preserved on update. -->

        ## Purpose
        <!-- Describe the responsibility of this directory in 1-2 sentences. -->

        ## Files

        {chr(10).join(file_summaries)}

        ## Key Patterns
        <!-- Document important conventions, abstractions, or patterns used here. -->

        ## Dependencies
        <!-- List notable internal or external dependencies. -->

        ## Notes
        <!-- Gotchas, TODOs, non-obvious decisions. -->
    """)


def main():
    repo_root = Path(subprocess.check_output(
        ['git', 'rev-parse', '--show-toplevel'], text=True
    ).strip())
    os.chdir(repo_root)

    created = []

    for dirpath in sorted(repo_root.rglob('*')):
        if not dirpath.is_dir():
            continue
        if not should_have_claude_md(dirpath):
            continue
        claude_md = dirpath / 'CLAUDE.md'
        if claude_md.exists():
            print(f"  [skip] {claude_md.relative_to(repo_root)} already exists")
            continue
        content = generate_claude_md(dirpath, repo_root)
        claude_md.write_text(content)
        created.append(str(claude_md.relative_to(repo_root)))
        print(f"  [+] created {claude_md.relative_to(repo_root)}")

    print(f"\nDone. Created {len(created)} CLAUDE.md file(s).")
    if created:
        print("Edit the '## Purpose' and '## Key Patterns' sections in each — those are preserved on update.")


if __name__ == '__main__':
    main()
